export const weatherActionTypes = {
  CREATE_SEARCH: "CREATE_SEARCH",
  CLEAR_SEARCH: "CLEAR_SEARCH",
  FETCH_CURRENT_WEATHER: "FETCH_CURRENT_WEATHER",
  FETCH_FORECAST_WEATHER: "FETCH_FORECAST_WEATHER"
};
